server.port=8080
spring.application.name=api-gateway

auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
bus.service.url=${BUS_SERVICE_URL:http://localhost:8082}
hotel.service.url=${HOTEL_SERVICE_URL:http://localhost:8083}
booking.service.url=${BOOKING_SERVICE_URL:http://localhost:8084}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8085}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8086}
review.service.url=${REVIEW_SERVICE_URL:http://localhost:8087}
