server.port=8080
spring.application.name=api-gateway

auth.service.url=http://localhost:8081
bus.service.url=http://localhost:8082
hotel.service.url=http://localhost:8083
booking.service.url=http://localhost:8084
payment.service.url=http://localhost:8085
notification.service.url=http://localhost:8086
review.service.url=http://localhost:8087
